version: '3.9'

services:
  backend:
    container_name: backend
    image: backend
    build:
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=      ${DATABASE_USER}
      - POSTGRES_PASSWORD=  ${DATABASE_PASSWORD}
      - POSTGRES_NAME=      ${DATABASE_NAME}
      - POSTGRES_HOST=      ${DATABASE_HOST}
      - POSTGRES_PORT=      ${DATABASE_PORT}
    ports:
       - "5432:5432"

volumes:
  pgdata: {}