version: '3.9'

services:
  backend:
    container_name: backend
    image: backend
    build:
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    container_name: db
    image: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    ports: 
      - "5432:5432"
volumes:
  pg-data: